name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Build and push the Docker image to Docker Hub
      - uses: actions/docker/login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t myimage .
      - run: docker tag myimage ${{ secrets.DOCKER_USERNAME }}/myimage:latest
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/myimage:latest
      # Connect to the Ubuntu server and deploy the new image
      - uses: actions/ssh-action@v0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          private-key: ${{ secrets.SERVER_KEY }}
          script: |
            # Stop the old container
            docker stop flashapp1
            # Pull the new image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/myimage:latest
            # Run the new container on port 3005
            docker run -d --name mycontainer -p 3005:3000 ${{ secrets.DOCKER_USERNAME }}/myimage:latest
